#!/bin/tcsh

set Repeats = $argv[1]
shift

foreach TestFile ($argv)
    set ResultFile = "TestResults/`echo $TestFile | sed -e 's/TestFiles\///' -e 's#/#_#g'`"
    rm -f $ResultFile
end
source shzzam_venv/bin/activate.csh >& /dev/null 
foreach Model (OpenAI Google)
    foreach TestFile ($argv)
        set ResultFile = "TestResults/`echo $TestFile | sed -e 's/TestFiles\///' -e 's#/#_#g'`"
        touch $ResultFile
        set Count = 1
        while ($Count <= $Repeats)
            @ Count++
            ShZZaM.py -q5 -M $Model -S OpenAI -p Vampire--- -m Vampire-SAT--- -v $TestFile | tee -a $ResultFile | grep 'RESULT:' | sed -e 's/RESULT: //' -e 's/\.\([A-Z][A-Z][A-Z]\)\.[^,]*/,\1/'
        end
    end
end
deactivate

